# Generated by Django 5.0.6 on 2025-10-09 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverificationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInvitationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del profesor a invitar', max_length=254, unique=True)),
                ('code', models.CharField(help_text='Código de invitación', max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Fecha de expiración')),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invitations', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invitation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Código de Invitación de Profesor',
                'verbose_name_plural': 'Códigos de Invitación de Profesores',
                'ordering': ['-created_at'],
            },
        ),
    ]
