# Generated by Django 5.0.6 on 2025-10-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacherinvitationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverificationcode',
            old_name='used',
            new_name='is_used',
        ),
        migrations.AddField(
            model_name='emailverificationcode',
            name='code_type',
            field=models.CharField(choices=[('EMAIL_VERIFICATION', 'Verificación de Email'), ('PASSWORD_RESET', 'Recuperación de Contraseña')], default='EMAIL_VERIFICATION', max_length=20),
        ),
    ]
