# Generated by Django 5.0.6 on 2025-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_used_emailverificationcode_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_timeout',
            field=models.IntegerField(default=30, help_text='Tiempo de inactividad en minutos antes de cerrar sesión automáticamente (5-120 minutos)'),
        ),
    ]
