# Generated by Django 5.0.6 on 2025-11-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_session_timeout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre completo del remitente', max_length=200)),
                ('email', models.EmailField(help_text='Email de contacto', max_length=254)),
                ('subject', models.CharField(choices=[('soporte', 'Soporte Técnico'), ('registro', 'Problema con Registro'), ('calificaciones', 'Consulta sobre Calificaciones'), ('profesor', 'Solicitud de Acceso como Profesor'), ('bug', 'Reportar un Error'), ('sugerencia', 'Sugerencia o Mejora'), ('otro', 'Otro')], help_text='Asunto del mensaje', max_length=50)),
                ('message', models.TextField(help_text='Contenido del mensaje')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False, help_text='Marca si el mensaje fue leído')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-created_at'],
            },
        ),
    ]
