# Generated by Django 5.0.6 on 2025-12-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ENROLLMENT_CREATED', 'Inscripción creada'), ('RESULTS_UPDATED', 'Resultados actualizados'), ('REPORT_READY', 'Reporte listo'), ('NEW_MESSAGE', 'Nuevo mensaje'), ('GENERAL', 'General')], default='GENERAL', max_length=40),
        ),
    ]
