# ==============================================
# DevTrack - Development Overrides
# Usado con: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
# ==============================================

services:
  # ==============================================
  # Backend Development
  # ==============================================
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      # Montar código fuente para hot reload
      - ./backend:/app
      # No montar __pycache__ (mejor performance)
      - /app/__pycache__
    environment:
      DJANGO_DEBUG: "True"
      DJANGO_SETTINGS_MODULE: config.settings
    command: python manage.py runserver 0.0.0.0:8000
    # Para debugging, puedes añadir:
    # stdin_open: true
    # tty: true

  # ==============================================
  # Frontend Development
  # ==============================================
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      # Montar código fuente para hot reload
      - ./frontend:/app
      # No montar node_modules (usar los del contenedor)
      - /app/node_modules
    ports:
      # Usar puerto 5173 de Vite en desarrollo
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8000
      VITE_TURNSTILE_SITE_KEY: ${VITE_TURNSTILE_SITE_KEY:-0x4AAAAAAB195XyO5y089iC-}
    command: npm run dev -- --host 0.0.0.0

  # ==============================================
  # Database Development
  # ==============================================
  db:
    # En desarrollo, exponer puerto para acceso directo
    ports:
      - "3306:3306"
