[phases.setup]
nixPkgs = ['python311', 'gcc', 'bash']
aptPkgs = ['default-libmysqlclient-dev', 'pkg-config']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r backend/requirements.txt'
]

[start]
cmd = 'bash start.sh'
