[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'gcc', 'bash']
aptPkgs = ['default-libmysqlclient-dev', 'pkg-config']

[phases.install]
cmds = [
  'pip3 install --user -r backend/requirements.txt'
]

[start]
cmd = 'bash start.sh'
