[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'python311Packages.virtualenv', 'gcc', 'bash']
aptPkgs = ['default-libmysqlclient-dev', 'pkg-config']

[phases.install]
cmds = [
  'python3 -m venv /opt/venv',
  '/opt/venv/bin/pip install -r backend/requirements.txt'
]

[start]
cmd = 'bash start.sh'
