[build]
builder = "NIXPACKS"
nixpacksConfigPath = "backend/nixpacks.toml"

[deploy]
startCommand = "cd backend && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --log-file -"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
