# Generated by Django 5.0.6 on 2025-10-09 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ENROLLMENT', 'Inscripción'), ('RESULT_CREATED', 'Resultado Creado'), ('RESULT_UPDATED', 'Resultado Actualizado'), ('EXERCISE_CREATED', 'Ejercicio Creado'), ('GENERAL', 'General')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='courses_not_user_id_11dad2_idx'), models.Index(fields=['user', 'is_read'], name='courses_not_user_id_0d96a8_idx')],
            },
        ),
    ]
