# Generated by Django 5.0.6 on 2025-10-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exercise',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Fecha límite de entrega', null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del ejercicio', null=True),
        ),
        migrations.AlterField(
            model_name='studentexerciseresult',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('RED', 'Rojo')], max_length=10),
        ),
    ]
