# Generated by Django 5.0.6 on 2025-10-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_exercise_unique_together_exercise_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentexerciseresult',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo')], max_length=10),
        ),
    ]
