# Generated by Django 5.0.6 on 2025-10-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_studentexerciseresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexerciseresult',
            name='comment',
            field=models.TextField(blank=True, help_text='Comentarios o retroalimentación del profesor', null=True),
        ),
    ]
