# Generated by Django 5.0.6 on 2025-11-27 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_studentexerciseresult_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexerciseresult',
            name='submission_file',
            field=models.FileField(blank=True, help_text='Archivo de solución (PDF, DOCX, XLSX)', null=True, upload_to='submissions/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx'])]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ENROLLMENT', 'Inscripción'), ('RESULT_CREATED', 'Resultado Creado'), ('RESULT_UPDATED', 'Resultado Actualizado'), ('EXERCISE_CREATED', 'Ejercicio Creado'), ('SUBMISSION_CREATED', 'Entrega Realizada'), ('GENERAL', 'General')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentexerciseresult',
            name='status',
            field=models.CharField(choices=[('GREEN', 'Verde'), ('YELLOW', 'Amarillo'), ('RED', 'Rojo'), ('SUBMITTED', 'Entregado')], max_length=10),
        ),
    ]
