# Generated by Django 5.0.6 on 2025-11-27 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_studentexerciseresult_submission_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='attachment',
            field=models.FileField(blank=True, help_text='Archivo adjunto para el ejercicio', null=True, upload_to='exercises/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'xlsx', 'zip', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
