# Generated by Django 5.0.6 on 2025-12-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_exercise_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexerciseresult',
            name='submission_text',
            field=models.TextField(blank=True, help_text='Solución en texto (máx 5000 caracteres)', null=True),
        ),
    ]
