# Generated by Django 5.2.5 on 2025-08-16 04:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del ejercicio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('difficulty', models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], default='EASY', max_length=20, verbose_name='Dificultad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_exercises', models.IntegerField(default=0, verbose_name='Total de ejercicios')),
                ('green_exercises', models.IntegerField(default=0, verbose_name='Ejercicios verdes')),
                ('yellow_exercises', models.IntegerField(default=0, verbose_name='Ejercicios amarillos')),
                ('red_exercises', models.IntegerField(default=0, verbose_name='Ejercicios rojos')),
                ('calculated_grade', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota calculada')),
                ('last_calculation', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Calificación del estudiante',
                'verbose_name_plural': 'Calificaciones de estudiantes',
                'ordering': ['-calculated_grade'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='Código estudiantil')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
            },
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GREEN', 'Verde - Completado correctamente'), ('YELLOW', 'Amarillo - Completado con errores menores'), ('RED', 'Rojo - No completado o con errores graves')], default='RED', max_length=10, verbose_name='Estado del ejercicio')),
                ('code_submission', models.TextField(blank=True, verbose_name='Código enviado')),
                ('onlinegdb_url', models.URLField(blank=True, verbose_name='URL de OnlineGDB')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de envío')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Ejercicio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Envío de ejercicio',
                'verbose_name_plural': 'Envíos de ejercicios',
                'ordering': ['-submission_date'],
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
